[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket="0.5.1"
tokio = { version = "1.40.0", features = ["full"] }
ws = { package = "rocket_ws", version = "0.1.1" }
axum = "0.7.7"
socketioxide = "0.14.1"